services:
  signaling:
    image: planning-poker-signaling:0.2.0
    hostname: signaling
    ports:
      - "8200:8080"
    networks:
      - planning-poker

  frontend:
    image: planning-poker-frontend:0.2.0
    hostname: frontend
    ports:
      - "8100:80"
    networks:
      - planning-poker


  gateway:
    image: planning-poker-gateway:0.2.0
    hostname: gateway
    command:
      ##
      # Providing Traefik configuration via CLI (mixture is not allowed):
      #
      - --log.level=DEBUG
      - --accesslog=true
      - --entrypoints.web.address=:80
      - --entrypoints.ws.address=:81
      - --providers.file.directory=/etc/traefik/services
      - --providers.file.watch=true
    ports:
      - "8000:80"
      - "8001:81"
    networks:
      - planning-poker

networks:
  planning-poker: {}
