FROM node:22.9-alpine3.20 AS build

WORKDIR /usr/src/app

COPY package*.json ./
COPY ./src ./src

RUN npm install

FROM build

WORKDIR /usr/src/app
EXPOSE 8080

CMD [ "node", "src/main/js/index.js" ]
